spring:
  application:
    name: time-note-backend
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB
server:
  port: 8081

# tim-note-jwt-secret-key-for-spring-boot-application-2024 有效期一天
jwt:
  secret: dGltZS1ub3RlLWp3dC1zZWNyZXQta2V5LWZvci1zcHJpbmctYm9vdC1hcHBsaWNhdGlvbi0yMDI0
  expiration: 86400000

# springdoc-openapi项目相关配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.note.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
